# Generated by Django 5.0.4 on 2024-04-06 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Olympiad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название олимпиады')),
                ('date_from', models.DateField(verbose_name='Дата начала олимпиады')),
                ('date_to', models.DateField(verbose_name='Дата окончания олимпиады')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('olymp_site', models.URLField(blank=True, null=True, verbose_name='Сайт олимпиады')),
                ('codeforces_tour', models.URLField(blank=True, null=True, verbose_name='Codeforces тур')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Полное название региона')),
                ('short_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Короткое название региона')),
                ('region_code', models.IntegerField(blank=True, null=True, verbose_name='Код региона')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('father_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WIN', 'Победитель'), ('PRI', 'Призер'), ('1', 'Диплом 1 степени'), ('2', 'Диплом 2 степени'), ('3', 'Диплом 3 степени'), ('PART', 'Участник')], max_length=10, verbose_name='Статус')),
                ('grade', models.IntegerField(blank=True, null=True, verbose_name='Класс')),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roi.olympiad', verbose_name='Олимпиада')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roi.region', verbose_name='Регион')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roi.student', verbose_name='Участник')),
            ],
        ),
        migrations.AddField(
            model_name='olympiad',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roi.region', verbose_name='Регион'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100, verbose_name='Название')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Короткое название')),
                ('day', models.CharField(blank=True, max_length=100, null=True, verbose_name='День')),
                ('max_score', models.IntegerField(default=100, verbose_name='Максимальный балл за задачу')),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roi.olympiad', verbose_name='Олимпиада')),
            ],
        ),
        migrations.CreateModel(
            name='PartyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Балл')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roi.party', verbose_name='Участник')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roi.task', verbose_name='Задача')),
            ],
        ),
    ]
