# Generated by Django 5.0.4 on 2024-04-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='olympiad',
            options={'verbose_name': 'Олимпиада', 'verbose_name_plural': 'Олимпиады'},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name': 'Участник олимпиады', 'verbose_name_plural': 'Участники олимпиады'},
        ),
        migrations.AlterModelOptions(
            name='partyresult',
            options={'verbose_name': 'Результат участника', 'verbose_name_plural': 'Результаты участников'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AddField(
            model_name='partyresult',
            name='rank',
            field=models.IntegerField(default=-1, verbose_name='Место'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Регион существует?'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_code',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Код региона'),
        ),
    ]
