# Generated by Django 5.0.4 on 2024-04-07 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roi', '0002_alter_olympiad_options_alter_party_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100, unique=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roi.region')),
            ],
        ),
    ]
