# Generated by Django 5.0.4 on 2024-04-07 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roi', '0004_rename_first_name_student_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partyresult',
            name='party',
        ),
        migrations.RemoveField(
            model_name='partyresult',
            name='task',
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WIN', 'Победитель'), ('PRI', 'Призер'), ('1', 'Диплом 1 степени'), ('2', 'Диплом 2 степени'), ('3', 'Диплом 3 степени'), ('PART', 'Участник')], max_length=10, verbose_name='Статус')),
                ('grade', models.IntegerField(blank=True, null=True, verbose_name='Класс')),
                ('rank', models.IntegerField(verbose_name='Место')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Итоговый балл')),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roi.olympiad', verbose_name='Олимпиада')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roi.region', verbose_name='Регион')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roi.student', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Участник олимпиады',
                'verbose_name_plural': 'Участники олимпиады',
            },
        ),
        migrations.CreateModel(
            name='ParticipantResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Балл')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roi.participant', verbose_name='Участник')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roi.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Результат участника',
                'verbose_name_plural': 'Результаты участников',
            },
        ),
        migrations.DeleteModel(
            name='Party',
        ),
        migrations.DeleteModel(
            name='PartyResult',
        ),
    ]
