# Generated by Django 5.0.4 on 2024-04-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roi', '0005_remove_partyresult_party_remove_partyresult_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='rank',
            field=models.IntegerField(blank=True, null=True, verbose_name='Место'),
        ),
    ]
