# Generated by Django 5.0.4 on 2024-04-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roi', '0006_alter_participant_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participantresult',
            old_name='party',
            new_name='participant',
        ),
    ]
